[source]
type = "stun"

# [source]
# type = "http"

# [source]
# type = "interface"
# name = "eth0"

versions = ["v4"]

# versions = ["v4", "v6"]

# Cloudflare Provider
[[providers]]
type = "cloudflare"
zone = "domain.com"
api_token = "TOKEN"

[[providers.domains]]
name = "*.domain.com" # Required
ttl = 1
proxied = false
comment = "Wildcard subdomain"

[[providers.domains]]
name = "domain.com" # Required
ttl = 1
proxied = false
comment = "Root domain"
