versions = ["v4", "v6"]
interval = "10s"

[source]
type = "stun"

# [source]
# type = "http"

# [source]
# type = "interface"
# name = "eth0"

[[providers]]
type = "cloudflare"
host = "example.com"
api_token = "API_KEY_HERE"
proxied = false
ttl = 0

[[providers]]
type = "dyndns"
host = "example.com"
username = "user"
password = "pass"
