name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64-musl
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64-musl
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-x86_64-gnu
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Linux-aarch64-gnu
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu

          - os-name: macOS-aarch64
            runs-on: macos-15
            target: aarch64-apple-darwin

          - os-name: macOS-x86_64
            runs-on: macos-15-intel
            target: x86_64-apple-darwin

          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: "stable"
          args: "--release --locked"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ddrs
          changes-file: CHANGELOG.md
          target: ${{ matrix.platform.target }}
